Added feature #2 (duplicated #57): now you can resize your tomb. The syntax is the same as 'create', then: tomb -s <size> -k <key> resize tombfile where: <size> is the new tombfile size <key> is the key to open the tomb (same mechanism as 'create')

diff --git a/src/tomb b/src/tomb
--- a/src/tomb
+++ b/src/tomb
@@ -27,6 +27,7 @@ TOMBOPENEXEC="tomb-open"
 typeset -a OLDARGS
 for arg in ${argv}; do OLDARGS+=($arg); done
 STEGHIDE=1
+RESIZE_SUITE=0
 MOUNTOPTS="rw,noatime,nodev"
 
 #declare global variables
@@ -103,7 +104,19 @@ check_bin() {
         error "Cannot find pinentry. Please install it."
         exit 1
     fi
- 
+
+    # check for resize tools
+    # incremental check!  
+    which e2fsck > /dev/null
+    if [ $? = 0 ]; then
+        RESIZE_SUITE=`expr $RESIZE_SUITE + 1`
+    fi
+
+    which resize2fs > /dev/null
+    if [ $? = 0 ]; then
+        RESIZE_SUITE=`expr $RESIZE_SUITE + 1`
+    fi
+
     # check for tomb-open script
     if [ "$0" = "./tomb" ]; then
 	TOMBOPENEXEC="./tomb-open"
@@ -983,7 +996,150 @@ umount_tomb() {
     return 0
 }
 
-# list all tombs mounted in a readable format
+# resize tomb
+resize_tomb() {
+    if ! [ ${CMD2} ]; then
+        error "No tomb name specified for resizing"
+        return 1
+    elif ! [ -r "${CMD2}" ]; then
+        error "Cannot find ${CMD2}"
+        return 1
+    fi
+
+    local c tombpass tombkey
+    local tombfile=`basename ${CMD2}`
+    local tombdir=`dirname ${CMD2}`
+    # make sure the file has a .tomb extension
+    local tombname=${tombfile%%\.*}
+    tombfile=${tombname}.tomb
+
+    if option_is_set -k ; then
+	    if [[ "`option_value -k`" == "-" ]]; then
+	        # take key from stdin
+	        local tombkeydir
+	        tombkeydir=`safe_dir`
+	        cat > ${tombkeydir}/stdin.tmp
+	        tombkey=${tombkeydir}/stdin.tmp
+	    else
+	        # take key from a file
+            tombkey=`option_value -k`
+	    fi
+    else
+	    # guess key as lying besides the tomb
+        tombkey=${tombdir}/${tombfile}.key
+    fi
+    
+    if ! [ -r ${tombkey} ]; then
+	    error "key file not found: ${tombkey}"
+	    error "operation aborted."
+	    return 1
+    fi
+
+    local tmp_resize=/tmp/tmbsrz
+    local newtombsize=$opts[-s]
+    local oldtombsize=`stat -c %s "${CMD2}" 2>/dev/null`
+	local mounted_tomb=`mount -l |
+        awk -vtomb="[$tombname]" '/^\/dev\/mapper\/tomb/ { if($7==tomb) print $1 }'`
+
+    if [ "$mounted_tomb" ]; then
+        error "the tomb $tombname is mounted: to resize, umount it ('tomb close $tombname' is your friend)."
+        return 1
+    fi
+
+    # MB to bytes conversion
+    newtombsize=`expr \( $newtombsize \* 1024 \) \* 1024 2> /dev/null`
+    
+    if ! [ "$newtombsize" ] ; then
+        error "You must specify the new size of $tombname"
+        return 1
+    elif [[ $newtombsize != <-> ]]; then
+        error "Size is not an integer"
+        return 1
+    elif [ "$newtombsize" -le "$oldtombsize" ]; then
+        error "the new size must be greater then old tomb size."
+        return 1
+    fi
+
+    local delta=`expr $newtombsize \- $oldtombsize`
+    
+    local tombsize_4k=`expr $delta \/ 1024`
+    tombsize_4k=`expr $tombsize_4k \/ 4 `
+    
+    act "Generating ${tombfile} of ${newtombsize}Mb (${tombsize_4k} blocks of 4Kb)"
+    "$DD" if=/dev/urandom bs=4k count=${tombsize_4k} of="${tmp_resize}"
+
+    if [ $? = 0 -a -e "${tmp_resize}" ]; then
+	    act "OK: `ls -lh ${tmp_resize}`"
+    else
+	    error "Error creating the extra resize $tmp_resize, operation aborted."
+	    exit 1
+    fi
+    
+    cat "${tmp_resize}" >> "${CMD2}"
+    "${WIPE}" "${tmp_resize}"
+    
+    local nstloop=`losetup -f`
+    if [ $? = 255 ]; then
+        error "too many tomb opened. Please close any of them to open another tomb"
+        return 1
+    fi
+    losetup -f "${CMD2}"
+    
+    local mapdate=`date +%s`
+    local mapper="tomb.${tombname}.${mapdate}.`basename $nstloop`"
+    
+    notice "Password is required for key ${keyname}"
+    for c in 1 2 3; do
+	    if [ $c = 1 ]; then
+	        tombpass=`exec_as_user ${TOMBEXEC} askpass ${keyname}`
+	    else
+	        tombpass=`exec_as_user ${TOMBEXEC} askpass "$keyname (retry $c)"`
+	    fi
+        (gpg --batch --passphrase-fd 0 --no-tty --no-options \
+            -d "${tombkey}" 2> /dev/null <<< ${tombpass} ) \
+            | cryptsetup --key-file - luksOpen ${nstloop} ${mapper}
+	    
+        unset tombpass
+	
+	    if [ -r /dev/mapper/${mapper} ]; then
+	        break;  # password was correct
+        fi
+    done
+
+    if ! [ -r /dev/mapper/${mapper} ]; then
+        error "failure mounting the encrypted file"
+        losetup -d ${nstloop}
+        return 1
+    fi
+
+    cryptsetup resize "${mapper}"
+    if [ $? != 0 ]; then
+        error "cryptsetup failed to resize $mapper"
+        losetup -d ${nstloop}
+        return 1
+    fi
+
+    e2fsck -f /dev/mapper/${mapper}
+    if [ $? != 0 ]; then
+        error "e2fsck failed to check $mapper"
+        losetup -d ${nstloop}
+        return 1
+    fi
+
+    resize2fs /dev/mapper/${mapper}
+    if [ $? != 0 ]; then
+        error "resize2fs failed to resize $mapper"
+        losetup -d ${nstloop}
+        return 1
+    fi
+
+    # close and free the loop device
+    cryptsetup luksClose "${mapper}"
+    losetup -d ${nstloop}
+
+    return 0
+}
+
 list_tombs() {
     if [ $1 ]; then
 	# list a specific tomb
@@ -1263,6 +1419,7 @@ main() {
     subcommands_opts[mktemp]=""
     subcommands_opts[source]=""
     subcommands_opts[status]=""
+    subcommands_opts[resize]="s: -size=s k: -key=k"
     ### Detect subcommand
     local -aU every_opts #every_opts behave like a set; that is, an array with unique elements
     for optspec in $subcommands_opts$main_opts; do
@@ -1339,6 +1496,11 @@ main() {
 	 umount) check_priv ; umount_tomb ${CMD2} ;;
 	  close) check_priv ; umount_tomb ${CMD2} ;;
 	   slam) check_priv ; SLAM=1; umount_tomb ${CMD2} ;;
+	 resize) if [ "$RESIZE_SUITE" != 2 ]; then
+                error "cannot find e2fsck or resize2fs. Cannot resize your tomb."
+                return 1
+            fi
+            check_priv ; resize_tomb ;;
 	   list) list_tombs ${CMD2} ;;
 	 status) launch_status ${CMD2} ;;
 	   help) usage ;;
